COUNTRY_TO_LANGUAGES = {
  :a1 => nil, # Anonymous Proxy
  :a2 => nil, # Satellite Provider
  :o1 => nil, # Other Country
  :ad => [:ca, :es, :fr], # Andorra
  :ae => [:ar], # United Arab Emirates
  :af => [:ps, :ar, :fa], # Afghanistan
  :ag => [:en], # Antigua and Barbuda
  :ai => [:en], # Anguilla
  :al => [:it, :sq], # Albania
  :am => [:hy], # Armenia
  :ao => [:pt], # Angola
  :ap => nil, # Asia/Pacific Region
  :aq => nil, # Antarctica
  :ar => [:es], # Argentina
  :as => [:en, :sm], # American Samoa
  :at => [:de], # Austria
  :au => [:en], # Australia
  :aw => [:nl], # Aruba
  :ax => [:sv], # Aland Islands
  :az => [:az], # Azerbaijan
  :ba => [:bs, :hr, :sr], # Bosnia and Herzegovina
  :bb => [:en], # Barbados
  :bd => [:bn, :en], # Bangladesh
  :be => [:fr, :nl, :de], # Belgium
  :bf => [:fr], # Burkina Faso
  :bg => [:bg], # Bulgaria
  :bh => [:ar, :en], # Bahrain
  :bi => [:fr, :rn], # Burundi
  :bj => [:fr], # Benin
  :bl => [:fr], # Saint Bartelemey
  :bm => [:en], # Bermuda
  :bn => [:ms], # Brunei Darussalam
  :bo => [:es, :qu, :ay], # Bolivia
  :bq => [:nl], # Bonaire, Saint Eustatius and Saba
  :br => [:pt], # Brazil
  :bs => [:en], # Bahamas
  :bt => [:dz], # Bhutan
  :bv => [:no], # Bouvet Island
  :bw => [:en, :tn], # Botswana
  :by => [:ru, :be], # Belarus
  :bz => [:en], # Belize
  :ca => [:fr, :en], # Canada
  :cc => [:en], # Cocos (Keeling) Islands
  :cd => [:fr, :kg, :ln], # Congo, The Democratic Republic of the
  :cf => [:fr, :sg], # Central African Republic
  :cg => [:fr, :kg, :ln], # Congo
  :ch => [:fr, :it, :de, :rm], # Switzerland
  :ci => [:fr], # Cote d'Ivoire
  :ck => [:en], # Cook Islands
  :cl => [:es], # Chile
  :cm => [:fr, :en], # Cameroon
  :cn => [:mn, :bo, :ug, :za], # China
  :co => [:es], # Colombia
  :cr => [:es], # Costa Rica
  :cu => [:es], # Cuba
  :cv => [:pt], # Cape Verde
  :cw => [:en, :nl], # Curacao
  :cx => [:en], # Christmas Island
  :cy => [:tr, :el], # Cyprus
  :cz => [:cs], # Czech Republic
  :de => [:de], # Germany
  :dj => [:fr, :ar], # Djibouti
  :dk => [:da], # Denmark
  :dm => [:en], # Dominica
  :do => [:es], # Dominican Republic
  :dz => [:ar, :fr], # Algeria
  :ec => [:es], # Ecuador
  :ee => [:et], # Estonia
  :eg => [:ar], # Egypt
  :eh => [:ar, :es], # Western Sahara
  :er => [:ar, :ti], # Eritrea
  :es => [:es, :ca], # Spain
  :et => [:am], # Ethiopia
  :eu => nil, # Europe
  :fi => [:sv, :fi], # Finland
  :fj => [:en, :fj, :hi, :ur], # Fiji
  :fk => [:en], # Falkland Islands (Malvinas)
  :fm => [:en], # Micronesia, Federated States of
  :fo => [:fo, :da], # Faroe Islands
  :fr => [:fr], # France
  :ga => [:fr], # Gabon
  :gb => [:en], # United Kingdom
  :gd => [:en], # Grenada
  :ge => [:ka], # Georgia
  :gf => [:fr], # French Guiana
  :gg => [:fr, :en], # Guernsey
  :gh => [:en], # Ghana
  :gi => [:en, :es], # Gibraltar
  :gl => [:kl], # Greenland
  :gm => [:en], # Gambia
  :gn => [:fr], # Guinea
  :gp => [:fr], # Guadeloupe
  :gq => [:pt,:es,:fr], # Equatorial Guinea
  :gr => [:el], # Greece
  :gs => [:en], # South Georgia and the South Sandwich Islands
  :gt => [:es], # Guatemala
  :gu => [:en, :ch], # Guam
  :gw => [:pt], # Guinea-Bissau
  :gy => [:en], # Guyana
  :hk => [:cn, :en], # Hong Kong
  :hm => [:en], # Heard Island and McDonald Islands
  :hn => [:es], # Honduras
  :hr => [:hr], # Croatia
  :ht => [:fr, :ht], # Haiti
  :hu => [:hu], # Hungary
  :id => [:id], # Indonesia
  :ie => [:ga, :en], # Ireland
  :il => [:he, :ar], # Israel
  :im => [:en, :gv], # Isle of Man
  :in => [:hi, :en], # India
  :io => [:en], # British Indian Ocean Territory
  :iq => [:ar, :ku], # Iraq
  :ir => [:fa], # Iran, Islamic Republic of
  :is => [:is], # Iceland
  :it => [:it], # Italy
  :je => [:en, :fr], # Jersey
  :jm => [:en], # Jamaica
  :jo => [:ar], # Jordan
  :jp => [:ja], # Japan
  :ke => [:en, :sw], # Kenya
  :kg => [:ky, :ru], # Kyrgyzstan
  :kh => [:km], # Cambodia
  :ki => [:en], # Kiribati
  :km => [:fr, :ar], # Comoros
  :kn => [:en], # Saint Kitts and Nevis
  :kp => [:ko], # Korea, Democratic People's Republic of
  :kr => [:ko], # Korea, Republic of
  :kw => [:ar], # Kuwait
  :ky => [:en], # Cayman Islands
  :kz => [:ru, :kk], # Kazakhstan
  :la => [:lo, :fr], # Lao People's Democratic Republic
  :lb => [:ar, :fr], # Lebanon
  :lc => [:en], # Saint Lucia
  :li => [:de], # Liechtenstein
  :lk => [:ta, :en, :si], # Sri Lanka
  :lr => [:en], # Liberia
  :ls => [:st, :en], # Lesotho
  :lt => [:lt], # Lithuania
  :lu => [:lb, :de, :fr], # Luxembourg
  :lv => [:lv], # Latvia
  :ly => [:ar], # Libyan Arab Jamahiriya
  :ma => [:ar, :fr], # Morocco
  :mc => [:fr, :oc], # Monaco
  :md => [:ro], # Moldova, Republic of
  :me => [:sr, :bs, :sq, :hr], # Montenegro
  :mf => [:fr], # Saint Martin
  :mg => [:fr, :mg], # Madagascar
  :mh => [:mh, :en], # Marshall Islands
  :mk => [:mk], # Macedonia
  :ml => [:fr], # Mali
  :mm => [:my], # Myanmar
  :mn => [:mn], # Mongolia
  :mo => [:cn, :pt], # Macao
  :mp => [:en, :ch], # Northern Mariana Islands
  :mq => [:fr], # Martinique
  :mr => [:ar, :wo], # Mauritania
  :ms => [:en], # Montserrat
  :mt => [:it, :en, :mt], # Malta
  :mu => [:fr, :en], # Mauritius
  :mv => [:dv], # Maldives
  :mw => [:en, :ny], # Malawi
  :mx => [:es], # Mexico
  :my => [:en, :ch], # Malaysia
  :mz => [:pt], # Mozambique
  :na => [:en], # Namibia
  :nc => [:fr], # New Caledonia
  :ne => [:fr], # Niger
  :nf => [:en], # Norfolk Island
  :ng => [:en], # Nigeria
  :ni => [:es, :en], # Nicaragua
  :nl => [:nl], # Netherlands
  :no => [:no, :nn, :nb], # Norway
  :np => [:ne], # Nepal
  :nr => [:na, :en], # Nauru
  :nu => [:en], # Niue
  :nz => [:en], # New Zealand
  :om => [:ar], # Oman
  :pa => [:es], # Panama
  :pe => [:es, :qu], # Peru
  :pf => [:fr], # French Polynesia
  :pg => [:ho, :en], # Papua New Guinea
  :ph => [:en], # Philippines
  :pk => [:en, :ur], # Pakistan
  :pl => [:pl], # Poland
  :pm => [:fr], # Saint Pierre and Miquelon
  :pn => [:en], # Pitcairn
  :pr => [:es, :en], # Puerto Rico
  :ps => [:ar, :hw], # Palestinian Territory
  :pt => [:pt], # Portugal
  :pw => [:en], # Palau
  :py => [:es, :gn], # Paraguay
  :qa => [:ar], # Qatar
  :re => [:fr], # Reunion
  :ro => [:ro], # Romania
  :rs => [:sr], # Serbia
  :ru => [:ru], # Russian Federation
  :rw => [:rw, :fr, :en], # Rwanda
  :sa => [:ar], # Saudi Arabia
  :sb => [:en], # Solomon Islands
  :sc => [:fr, :en], # Seychelles
  :sd => [:ar, :en], # Sudan
  :se => [:sv], # Sweden
  :sg => [:en, :ms, :ta, :cn], # Singapore
  :sh => [:en], # Saint Helena
  :si => [:sl], # Slovenia
  :sj => [:no, :nb, :nn], # Svalbard and Jan Mayen
  :sk => [:sk], # Slovakia
  :sl => [:en], # Sierra Leone
  :sm => [:it], # San Marino
  :sn => [:fr, :wo, :ff], # Senegal
  :so => [:so, :ar], # Somalia
  :sr => [:nl], # Suriname
  :ss => [:en], # South Sudan
  :st => [:pt], # Sao Tome and Principe
  :sv => [:es], # El Salvador
  :sx => [:nl, :en], # Sint Maarten
  :sy => [:ar], # Syrian Arab Republic
  :sz => [:ss, :en], # Swaziland
  :tc => [:en], # Turks and Caicos Islands
  :td => [:fr, :en], # Chad
  :tf => [:fr], # French Southern Territories
  :tg => [:fr], # Togo
  :th => [:th], # Thailand
  :tj => [:tg, :ru], # Tajikistan
  :tk => [:sm, :en], # Tokelau
  :tl => [:pt], # Timor-Leste
  :tm => [:ru, :tk], # Turkmenistan
  :tn => [:ar, :fr], # Tunisia
  :to => [:en, :to], # Tonga
  :tr => [:tr], # Turkey
  :tt => [:en], # Trinidad and Tobago
  :tv => [:en], # Tuvalu
  :tw => [:cn], # Taiwan
  :tz => [:sw, :en], # Tanzania, United Republic of
  :ua => [:uk], # Ukraine
  :ug => [:en, :sw], # Uganda
  :um => [:en], # United States Minor Outlying Islands
  :us => [:en, :es], # United States
  :uy => [:es], # Uruguay
  :uz => [:uz], # Uzbekistan
  :va => [:la, :fr, :it], # Holy See (Vatican City State)
  :vc => [:en], # Saint Vincent and the Grenadines
  :ve => [:es], # Venezuela
  :vg => [:en], # Virgin Islands, British
  :vi => [:en], # Virgin Islands, U.S.
  :vn => [:vi], # Vietnam
  :vu => [:fr, :en, :bi], # Vanuatu
  :wf => [:fr], # Wallis and Futuna
  :ws => [:sm, :en], # Samoa
  :ye => [:ar], # Yemen
  :yt => [:fr], # Mayotte
  :za => [:af, :en, :nr, :st, :ss, :ts, :tn, :ve, :xh, :zu], # South Africa
  :zm => [:en], # Zambia
  :zw => [:ny, :en, :nd, :ts, :sn, :st, :tn, :ve, :xh] # Zimbabwe
}
